### ISSUE TITLE
Waspai audio to AudioSource

### ISSUE THREAD

**Issue by Adz10kvtech** [hallidev/UnityWasapiAudio#2]
Thanks very much for this repo.

Is it possible to grab the WASAPI with cs.core and link it somehow to a Audio Source? We are trying to filter out desktop sounds from echoing over the microphone via a filter when using VoIP. 

Thanks again.

**Comment by hallidev** [comment]
Something like that might be possible but that’s way over my head. I wouldn’t know where to start

**Comment by Adz10kvtech** [comment]
Thanks for the reply
