### ISSUE TITLE
The GetSpectrumData returns an array of 0's on Loopback capture type

### ISSUE THREAD

**Issue by mariaheine** [hallidev/UnityWasapiAudio#5]
Environment: Unity 2020.2.1f1, tried in playmode in editor, didn't try building yet.

Expected behaviour: `WasapiAudioSource`'s method `GetSpectrumData()` returns proper spectrum data while `Loopback capture type` is selected and a sound is being played in background.

Actual behaviour: `GetSpectrumData()` returns an array of correct spectrum size but the array is filled with floats of value 0. As a result after entering the Playmode on freshly cloned repo nothing at al happens. 

> Important: On Microphone capture type the spectrum data is being captured correctly. 

Debugging: I don't know almost anything about cscore yet and as far as I got was to establish that `WasapiCapture` seems to read a correct capture device being my "Speakers (Realtek High Definition Audio)", but already at the level of `GetFftData` of `BasicSpectrumProvider` the float array is just an array of 0's and a call to the inherited `IsNewDataAvailable` property of `FftProvider` always returns false.

I attach the picture with my log of the function where I have hit the wall since it seems further debugging would require in depth understanding of cscore.

![image](https://user-images.githubusercontent.com/24575912/114920528-d0de2800-9e29-11eb-8844-c74ba7b16f9d.png)

I fear this will be likely some device related issue :/ Also super thanks for this cool repo, the microphone capture type works and ability to attach filters is beyond cool, I just wish the loopback worked for me.

**Comment by hallidev** [comment]
I suspect it's something with your device as well. One thing you can do is try to switch your default audio device away from and back to "Speakers (Realtek High Definition Audio)" in Windows settings to see if that helps. I have the same exact setup on my machine:

![image](https://user-images.githubusercontent.com/16142069/114925252-dd985700-9dfc-11eb-8867-31670292c2f8.png)

If you open the ```WasapiAudio``` class, you can see what it's doing to get the audio device for Loopback / Microphone:

```
switch (_captureType)
{
    case WasapiCaptureType.Loopback:
        _wasapiCapture = new WasapiLoopbackCapture();
        break;
    case WasapiCaptureType.Microphone:
        MMDevice defaultMicrophone;
        using (var deviceEnumerator = new MMDeviceEnumerator())
        {
            defaultMicrophone = deviceEnumerator.GetDefaultAudioEndpoint(DataFlow.Capture, Role.Communications);
        }
        _wasapiCapture = new WasapiCapture();
        _wasapiCapture.Device = defaultMicrophone;
        break;
    default:
        throw new InvalidOperationException("Unhandled WasapiCaptureType");
}
```

You can try playing around with the MMDeviceEnumerator and pick "Microphone" to run the code against other devices. I'm actually not familiar with the guts of CSCore either. I just built this little Unity wrapper for other Unity devs.

By looking at ```WasapiLoopbackCapture``` inside CSCore, this is what it's doing to get the loopback device:

```
protected override MMDevice GetDefaultDevice() => MMDeviceEnumerator.DefaultAudioEndpoint(DataFlow.Render, Role.Console);
```

I'm bummed to hear this is giving you issues - generally I think it has been working for people. Hope you can get it fixed though and sorry I couldn't help more.

**Comment by mariaheine** [comment]
I tried switching to `Role.Multimedia` as defined [here in cscore docs](http://filoe.github.io/cscore/sharpDox/1.2.0-release/#type/Role) and some other combinations of these two enums but still float arrays remained unimpressed.

Oddly Audacity has no issues recording Wasapi loopback sound for me, mmm.

Also I only have one device in sound output settings so can't really change that.

Oh well well, I guess it's just my old computer doing tricks on me, but at least the microphone part is working so thats cool for a while and I can already write my code against that since the output spectrum data will have the same format obviously independently whether its loopback or microphone.

If I stumble upon a fix to the issue I will put it here aswell, but otherwise I guess that can be closed.

**Comment by hallidev** [comment]
Please do comment if you find a fix. Wish I could help more. 

One last thing to check would be volume levels. The loopback audio data should be independent of volume, but double check that none of your devices are muted in the windows sound mixer settings. That’s the only other thing I can think of

**Comment by mariaheine** [comment]
Omg I feel beyond stupid 🤦‍♀️ I must have muted Unity alone during work, it is working :picard_facepalm: But yaaay, it works now

**Comment by hallidev** [comment]
Lol too funny :) Glad it's working!
